language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer create-project kenjis/codeigniter-composer-installer codeigniter
  - cd codeigniter
  - composer require kenjis/codeigniter-cli:1.0.x@dev --dev
  - php vendor/kenjis/codeigniter-cli/install.php
  - cd vendor/kenjis/codeigniter-cli
  - composer install

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
